/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author andre
 */
public class vistaMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vistaMenuPrincipal.class.getName());

    /**
     * Creates new form vistaMenuPrincipal
     */
    public vistaMenuPrincipal() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMArchivos = new javax.swing.JMenu();
        jMAlumnos = new javax.swing.JMenu();
        Menuitem1Alumnos = new javax.swing.JMenuItem();
        jMMaterias = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMInscripciones = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem_Inscripciones = new javax.swing.JMenuItem();
        jMCargaDeNotas = new javax.swing.JMenu();
        jMConsultas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setText("Sistema de gestion de la ULP");

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel1)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel1)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        jMArchivos.setText("Archivos");
        jMenuBar1.add(jMArchivos);

        jMAlumnos.setText("Alumnos");

        Menuitem1Alumnos.setText("Formulario de Alumnos");
        Menuitem1Alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menuitem1AlumnosActionPerformed(evt);
            }
        });
        jMAlumnos.add(Menuitem1Alumnos);

        jMenuBar1.add(jMAlumnos);

        jMMaterias.setText("Materias");

        jMenuItem2.setText("Formulario de Materias");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMMaterias.add(jMenuItem2);

        jMenuBar1.add(jMMaterias);

        jMInscripciones.setText("Inscripciones");

        jMenuItem3.setText("Manejo de Inscripciones");
        jMInscripciones.add(jMenuItem3);

        jMenuItem_Inscripciones.setText("Inscripciones");
        jMenuItem_Inscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_InscripcionesActionPerformed(evt);
            }
        });
        jMInscripciones.add(jMenuItem_Inscripciones);

        jMenuBar1.add(jMInscripciones);

        jMCargaDeNotas.setText("Carga de Notas");
        jMenuBar1.add(jMCargaDeNotas);

        jMConsultas.setText("Consultas");
        jMenuBar1.add(jMConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menuitem1AlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menuitem1AlumnosActionPerformed
        vistaAlumno ventanitaAlumno = new vistaAlumno();
        jDesktopPane1.add(ventanitaAlumno);
        ventanitaAlumno.setVisible(true);
       //ventanitaAlumno.setSize(jDesktopPane1.getSize());
        ventanitaAlumno.setLocation(05,05);
    }//GEN-LAST:event_Menuitem1AlumnosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        vistaMaterias ventanitaMaterias = new vistaMaterias();
        jDesktopPane1.add(ventanitaMaterias);
        ventanitaMaterias.setVisible(true);
        ventanitaMaterias.setLocation(05, 05);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem_InscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_InscripcionesActionPerformed
        vistaInscripcion inscripcion = new vistaInscripcion();
        jDesktopPane1.add(inscripcion);
        inscripcion.setVisible(true);
        inscripcion.setLocation(05,05);       
    }//GEN-LAST:event_jMenuItem_InscripcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vistaMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menuitem1Alumnos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMAlumnos;
    private javax.swing.JMenu jMArchivos;
    private javax.swing.JMenu jMCargaDeNotas;
    private javax.swing.JMenu jMConsultas;
    private javax.swing.JMenu jMInscripciones;
    private javax.swing.JMenu jMMaterias;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem_Inscripciones;
    // End of variables declaration//GEN-END:variables
}
